name: OnTheWay
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

 #맵관련
  kakao_map_plugin: ^0.3.1
  webview_flutter: ^4.9.0
  location: ^5.0.3

  http: ^1.2.2
#    http: ^0.13.1
  cloud_functions: ^5.1.2
  webview_flutter_wkwebview: ^3.15.0
  webview_flutter_android: ^3.16.7
#  webview_cookie_manager: ^2.0.6
  geolocator: ^13.0.1
  path_provider: ^2.1.4


  permission_handler: ^11.3.1


  firebase_core: ^3.5.0
  firebase_database: ^11.1.3
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.2
  firebase_messaging: ^15.1.2

  flutter_form_builder: ^9.4.1
  shared_preferences: ^2.3.2
  flutter_secure_storage: ^9.2.2
  intl: ^0.19.0
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.8

  #인증 및 별제 관련
#  twilio_flutter: 0.0.9
  iamport_flutter: ^0.10.19
  url_launcher: ^6.3.0
  app_links: ^6.3.2
  json_annotation: ^4.9.0

  #채팅 오픈소스
  firebase_storage: ^12.3.1
  image_picker: ^1.1.2
  rxdart: ^0.28.0
  flutter_chat_bubble: ^2.0.2

  #이메일인증
  google_sign_in: ^6.2.1

  #학점 관리
  font_awesome_flutter: ^10.7.0
  flutter_rating_bar: ^4.0.1

#  로티
  lottie: ^3.1.2


  #피그마 디자인
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1

  #프로필 이미지 변경시 자르기
  image_cropper: ^5.0.1

  #아이콘 배지
  flutter_app_badge: ^2.0.2

  #포그라운드 푸시알림
  flutter_local_notifications: ^17.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/noimage.jpeg
    - assets/blankimage.png
    - assets/avatar.png
    - assets/ava.png


    - assets/lottie/check_indigo.json




    - assets/images/logo-toss-pay.png
    - assets/images/Toss_Symbol_Primary.png
    - assets/images/payment_icon_yellow_large.png
    - assets/images/payment_icon_yellow_medium.png
    - assets/images/payment_icon_yellow_small.png
    - assets/images/LoginLogo.png
    - assets/images/LoginLogo2.png
    - assets/images/FindPassword.png
    - assets/images/RateStar.png



#    pigma 디자인 투입
    - assets/pigma/notifications.svg
    - assets/pigma/location.svg
    - assets/pigma/dollar_circle.svg
    - assets/pigma/vuesaxbulkhouse.svg
    - assets/pigma/Ellipse.svg
    - assets/pigma/pen.svg
    - assets/pigma/book.svg
    - assets/pigma/chatbubbles.svg
    - assets/pigma/footsteps.svg
    - assets/pigma/person.svg
    - assets/pigma/school.svg
    - assets/pigma/ellipsis.svg
    - assets/pigma/ellipsis_white.svg
    - assets/pigma/notification_white.svg
    - assets/pigma/write_locate.svg
    - assets/pigma/arrow.svg
    - assets/pigma/close_eye.svg
    - assets/pigma/open_eye.svg
    - assets/pigma/check_autologin.svg
    - assets/pigma/Polygon.svg
    - assets/pigma/x.svg
    - assets/pigma/Serch.svg
    - assets/pigma/map.svg
    - assets/pigma/compass.svg
    - assets/pigma/notifications_indigo.svg
    - assets/pigma/chatbubbles_indigo.svg
    - assets/pigma/person_indigo.svg
    - assets/pigma/trash-bin_indigo.svg
    - assets/pigma/exit_indigo.svg
    - assets/pigma/bank.svg
    - assets/pigma/trash-bin_white.svg
    - assets/pigma/exit_white.svg
    - assets/pigma/account_circle.svg
    - assets/pigma/cnuLogo.svg
    - assets/pigma/school_indigo.svg
    - assets/pigma/Toss_Symbol.svg

    - assets/pigma/more_vert_5F6368.svg
    - assets/pigma/more_vert_AAAAAA.svg
    - assets/pigma/more_vert_white.svg
    - assets/pigma/user_block_management.svg




  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 300
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 400
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 800
