name: OnTheWay
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

 #맵관련
  kakao_map_plugin: ^0.2.4
  webview_flutter: ^4.0.0
  location: ^5.0.3
  http: ^1.0.0
  cloud_functions: ^4.6.0
  webview_flutter_wkwebview: ^3.10.2
  webview_flutter_android: ^3.16.0
  webview_cookie_manager: ^2.0.6

  firebase_core: ^2.21.0
  firebase_auth: "^4.7.2"
  firebase_dynamic_links: ^5.3.4
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  flutter_form_builder: ^9.1.1
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5

  #애니메이션
  lottie: ^2.7.0


  #채팅 오픈소스
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  rxdart: ^0.27.7
  flutter_chat_bubble: ^2.0.2

  #이메일인증
  google_sign_in: ^6.1.6

  #학점 관리
  font_awesome_flutter: ^10.7.0
  flutter_rating_bar: ^4.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/noimage.jpeg
    - assets/blankimage.png
    - assets/avatar.png
    - assets/ava.png

    - assets/lottie/Animation.json
    - assets/lottie/Circle.json
    - assets/lottie/BoardColor.json
    - assets/lottie/AppbarColor.json
    - assets/lottie/blue.json
    - assets/lottie/blue2.json
    - assets/lottie/blue3.json
    - assets/lottie/pink.json
    - assets/lottie/puple.json
    - assets/lottie/orange.json
    - assets/lottie/walk.json
    - assets/lottie/CheckTest.json
    - assets/lottie/CheckTest2.json
    - assets/lottie/login.json
    - assets/lottie/send2.json
    - assets/lottie/loading.json
    - assets/lottie/loading_indigo.json



