name: OnTheWay
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

 #맵관련
  kakao_map_plugin: ^0.2.4
  webview_flutter: ^4.0.0
  location: ^5.0.3
  http: ^1.1.0
#    http: ^0.13.1
  cloud_functions: ^4.6.0
  webview_flutter_wkwebview: ^3.10.2
  webview_flutter_android: ^3.16.0
  webview_cookie_manager: ^2.0.6
  geolocator: ^11.1.0
  path_provider: ^2.1.3

#  flutter_background_geolocation: ^4.15.5
  background_locator_2: ^2.0.6
  permission_handler: ^11.0.0
#  flutter_inappwebview: ^6.0.0

  firebase_core: ^2.21.0
  firebase_database: ^10.4.0
  firebase_auth: "^4.7.2"
  firebase_dynamic_links: ^5.3.4
  cloud_firestore: ^4.13.6
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^16.3.0
  flutter_form_builder: ^9.1.1
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.5

  #인증 및 별제 관련
#  twilio_flutter: 0.0.9
  iamport_flutter: any
  url_launcher: ^6.0.4
  app_links: ^3.5.1
  json_annotation: ^4.8.1

  #애니메이션
  lottie: ^2.7.0


  #채팅 오픈소스
  firebase_storage: ^11.6.0
  image_picker: ^1.0.7
  rxdart: ^0.27.7
  flutter_chat_bubble: ^2.0.2

  #이메일인증
  google_sign_in: ^6.1.6

  #학점 관리
  font_awesome_flutter: ^10.7.0
  flutter_rating_bar: ^4.0.1


  #피그마 디자인
  flutter_svg: ^2.0.10+1
  google_fonts: 6.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/noimage.jpeg
    - assets/blankimage.png
    - assets/avatar.png
    - assets/ava.png

    - assets/lottie/Animation.json
    - assets/lottie/BoardColor.json
    - assets/lottie/AppbarColor.json
    - assets/lottie/blue.json
    - assets/lottie/blue2.json
    - assets/lottie/blue3.json
    - assets/lottie/puple.json


    - assets/lottie/walk.json
    - assets/lottie/login.json
    - assets/lottie/smile.json
    - assets/lottie/loading_indigo.json
    - assets/lottie/check1.json
    - assets/lottie/check_indigo.json
    - assets/lottie/clap.json
    - assets/lottie/congratulation.json
    - assets/lottie/clapCute.json
    - assets/lottie/createSuccess.json
    - assets/lottie/payment_appbar.json
    - assets/lottie/imageSending.json


    - assets/images/Toss_Symbol_Primary.png
    - assets/images/payment_icon_yellow_large.png
    - assets/images/payment_icon_yellow_medium.png
    - assets/images/payment_icon_yellow_small.png
    - assets/images/LoginLogo.png
    - assets/images/LoginLogo2.png

    - assets/fonts/

#    pigma 디자인 투입
    - assets/pigma/notifications.svg
    - assets/pigma/location.svg
    - assets/pigma/dollar_circle.svg
    - assets/pigma/vuesaxbulkhouse.svg
    - assets/pigma/Ellipse.svg
    - assets/pigma/pen.svg
    - assets/pigma/book.svg
    - assets/pigma/chatbubbles.svg
    - assets/pigma/footsteps.svg
    - assets/pigma/person.svg
    - assets/pigma/school.svg
    - assets/pigma/ellipsis.svg
    - assets/pigma/ellipsis_white.svg
    - assets/pigma/notification_white.svg

  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 300
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 400
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 800
