# platform 설정 및 기본 설정
platform :ios, '14.0'  # iOS 13.0으로 설정

# CocoaPods analytics 비활성화
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

# 프로젝트 설정
project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

# flutter_root 경로 설정
def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

# Flutter podhelper 파일 로드
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

# Flutter iOS podfile 설정
flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static  # Add this line
  use_modular_headers!

  # Firebase 및 Google Sign-In 관련 pod 추가
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  # Firebase Auth 추가
  pod 'Firebase/Auth'
  
  # Google Sign-In 추가
  pod 'GoogleSignIn'

  # Firebase Functions 추가
  pod 'Firebase/Functions'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

# 추가 빌드 설정
post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
